from django.conf.urls import patterns, include, url
from liga import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('liga.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', views.home, name='home'),
    url(r'^leagues/', views.leagues, name='leagues'),
    url(r'^league/(?P<l_id>\d+)/', views.league, name='league'),
    url(r'^team/(?P<t_id>\d+)/(?P<l_id>\d+)/', views.team, name='team'),
    url(r'^currentteamsquad/(?P<t_id>\d+)/', views.currentteamsquad, name='currentteamsquad'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^newplayer/', views.newplayer, name='newplayer'),
    url(r'^newreferee/', views.newreferee, name='newreferee'),
    url(r'^newcoach/', views.newcoach, name='newcoach'),
    url(r'^newteam/', views.newteam, name='newteam'),
    url(r'^newleague/', views.newleague, name='newleague'),
    url(r'^players/', views.players, name='players'),
    url(r'^referees/', views.referees, name='referees'),
    url(r'^coaches/', views.coaches, name='coaches'),
    url(r'^teams/', views.teams, name='teams'),
    url(r'^deleteplayer/(?P<p_id>\d+)/', views.deleteplayer, name='deleteplayer'),
    url(r'^deletereferee/(?P<r_id>\d+)/', views.deletereferee, name='deletereferee'),
    url(r'^deletecoach/(?P<c_id>\d+)/', views.deletecoach, name='deletecoach'),
    url(r'^deleteteam/(?P<t_id>\d+)/', views.deleteteam, name='deleteteam'),
    url(r'^editteam/(?P<t_id>\d+)/', views.editteam, name='editteam'),
    url(r'^deleteplayerfromteam/(?P<p_id>\d+)/(?P<t_id>\d+)/', views.deleteplayerfromteam, name='deleteplayerfromteam'),
    url(r'^editteamcoach/(?P<t_id>\d+)/', views.editteamcoach, name='editteamcoach'),
    url(r'^editleagueteams/(?P<l_id>\d+)/', views.editleagueteams, name='editleagueteams'),
    url(r'^deleteteamfromleague/(?P<t_id>\d+)/(?P<l_id>\d+)/', views.deleteteamfromleague, name='deleteteamfromleague'),
    url(r'^finishleague/(?P<l_id>\d+)/', views.finishleague, name='finishleague'),
    url(r'^deleteleague/(?P<l_id>\d+)/', views.deleteleague, name='deleteleague'),
    url(r'^matches/(?P<t_id>\d+)/(?P<l_id>\d+)/', views.matches, name='matches'),
    url(r'^newmatch/(?P<t_id>\d+)/(?P<l_id>\d+)/', views.newmatch, name='newmatch'),
    url(r'^match/(?P<m_id>\d+)/', views.match, name='match'),
    url(r'^addgoal/(?P<m_id>\d+)/(?P<t_id>\d+)/', views.addgoal, name='addgoal'),
    url(r'^deletegoal/(?P<g_id>\d+)/(?P<m_id>\d+)/', views.deletegoal, name='deletegoal'),
    url(r'^addstats/(?P<m_id>\d+)/(?P<t_id>\d+)/', views.addstats, name='addstats'),
    url(r'^deletestats/(?P<s_id>\d+)/(?P<m_id>\d+)/', views.deletestats, name='deletestats'),
    url(r'^addsub/(?P<m_id>\d+)/(?P<t_id>\d+)/', views.addsub, name='addsub'),
    url(r'^deletesub/(?P<s_id>\d+)/(?P<m_id>\d+)/', views.deletestats, name='deletesub'),
)